[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "channels[redis]>=4.2.0",
    "daphne>=4.1.2",
    "django>=5.1.7",
    "django-htmx>=1.23.0",
]
